---
- name: Install required dracut related packages
  package:
    name: '{{ item }}'
  become: True
  loop:
    - dracut-fips
    - dracut-fips-aesni

- name: Regenerate the initramfs file
  command: dracut -v -f
  become: True

- name: Add fips=1 to GRUB_CMDLINE_LINUX
  lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX="(.*)"'
    line: 'GRUB_CMDLINE_LINUX="fips=1 \1"'
    backrefs: yes
  become: True

- name: Apply the changes to /etc/default/grub
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
  become: True

- name: Reboot
  become: True
  reboot:
